app/promo/forms.py
"""
Form Class for Promo Modules
"""

from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import InputRequired, DataRequired, Length, Email
from wtforms.fields.html5 import DateField


class FlightForm(FlaskForm):
    """
    Form Class for Flights

    email           =   Email
    place_from      =   String
    place_to        =   String
    departure_date  =   Date
    arrival_date    =   Date
    budget_range    =   Float
    head_count      =   Integer
    """

    email = StringField('Email Address',
                        validators=[InputRequired(message='Please insert an Email Address'),
                                    Email(
                                        message='Please input a valid Email Address'),
                                    Length(max=100)])
    place_from = StringField('Departure Location',
                             validators=[InputRequired(message='Please insert a Departure Location'),
                                         Length(max=100)])
    place_to = StringField('Arrival Location',
                           validators=[InputRequired(message='Please insert an Arrival Location'),
                                       Length(max=100)])
    departure_date = DateField('Departure Date',
                               validators=[InputRequired(message='Please enter a Departure Date')])
    arrival_date = DateField('Arrival Date',
                             validators=[InputRequired(message='Please enter an Arrival Date')])
    budget_range = IntegerField('Budget Range',
                              validators=[InputRequired(message='Please enter a Budget Range')])
    head_count = IntegerField('Head Count',
                              validators=[InputRequired(message='Please enter the head count')])
    recaptcha = RecaptchaField()
    submit = SubmitField('Submit')


class HotelForm(FlaskForm):
    """
    Form Class for Hotels.

    Email           =   Email
    Hotel Location  =   String
    Check in Date   =   Date
    Check out Date  =   Date
    Number of Rooms =   Integer
    Budget Range    =   Float
    """
    email = StringField('Email Address',
                        validators=[DataRequired('Please insert an Email Address'),
                                    Email(
                                        message='Please insert a valid Email Address'),
                                    Length(max=100)])
    hotel_location = StringField('Hotel Location',
                                 [DataRequired('Please insert a location for your Hotel'),
                                  Length(max=100)])
    check_in_date = DateField('Check in Date',
                              [DataRequired('Please enter a Check in Date')])
    check_out_date = DateField('Check out Date',
                               [DataRequired('Please enter a Check out Date')])
    number_of_rooms = IntegerField('Number of Rooms',
                                   [DataRequired('Please Enter number of Rooms needed')])
    budget_range = IntegerField('Budget Range',
                              [DataRequired('Please enter a Budget Range')])
    recaptcha = RecaptchaField()
    submit = SubmitField('Submit')

app/promo/routes.py
"""
This is the routes file for promo
"""
from flask import Blueprint, render_template, request, url_for, redirect
from app.models import Packages, HotelBookings, FlightBooking, DB
from app.promo import forms
import stripe

MOD_PROMO = Blueprint('promo', __name__, template_folder='templates',
                      static_folder='static', static_url_path='/%s' % __name__)

pubkey = 'pk_test_GjK3GmJJ1exs60wIcgTpfggq'
secretkey = 'sk_test_RXyvP1FBgkRyCwyEBGyZeymo'

stripe.api_key = secretkey


@MOD_PROMO.route('/')
def promos():
    """ Promos """
    packages = Packages.query.order_by(Packages.package_id.desc()).all()
    return render_template("packages.html", packages=packages)


@MOD_PROMO.route('/package/<int:package_id>')
def package(package_id):
    """ Package """
    packages = Packages.query.filter_by(package_id=package_id).all()
    return render_template('getpackage.html', packages=packages, pubkey=pubkey)


@MOD_PROMO.route('/flights/confirm')
def confirmflight():
    """ Flight Confirmation """
    return render_template("flightconfirmation.html")


@MOD_PROMO.route('/bookings/confirm')
def confirmhotel():
    """ Hotel Confirmation """
    return render_template("hotelconfirmation.html")

@MOD_PROMO.route('/flights', methods=['GET', 'POST'])
def flights():
    """ Flights """
    form = forms.FlightForm()
    # print(form.errors)
    if form.validate_on_submit():
        flight = FlightBooking(fbooking_email=form.email.data, fbooking_departure=form.place_from.data,
                               fbooking_arrival=form.place_to.data, fbooking_departure_date=form.departure_date.data, fbooking_arrival_date=form.arrival_date.data,
                               fbooking_budget_range=form.budget_range.data, fbooking_head_count=form.head_count.data)
        DB.session.add(flight)
        DB.session.commit()
        return redirect(url_for("promo.confirmflight", code=307))
    print(form.errors)
    return render_template("flightbooking.html", form=form)


@MOD_PROMO.route('/bookings', methods=['GET', 'POST'])
def bookings():
    """ Bookings """
    form = forms.HotelForm()
    if form.validate_on_submit():
        hotel = HotelBookings(hbooking_email=form.email.data, hbooking_location=form.hotel_location.data, hbooking_check_in=form.check_in_date.data,
                              hbooking_check_out=form.check_out_date.data, hbooking_number_of_rooms=form.number_of_rooms.data, hbooking_budget_range=form.budget_range.data)
        DB.session.add(hotel)
        DB.session.commit()
        return redirect(url_for("promo.confirmhotel", code=307))
    print(form.errors)
    return render_template("hotelbooking.html", form=form)
  
@MOD_PROMO.route('/packagepayment/confirm')
def confirmpromo():
    """ Payment Confimation """
    return render_template("confirmpayment.html")

@MOD_PROMO.route('/packagepayment/<int:package_id>', methods=['POST'])
def pay(package_id):
    """ Payment Server Side """
    print(request.form)
    packages = Packages.query.filter_by(package_id=package_id).all()

    customer = stripe.Customer.create(
        email=request.form['stripeEmail'], source=request.form['stripeToken'])

    for items in packages:
        charge = stripe.Charge.create(
            customer=customer.id,
            amount=items.package_price * 100,
            currency="php",
            description=items.package_name
    )
    return redirect(url_for("promo.confirmpromo", code=307))

app/promo/templates/confirmpayment.html
{% extends 'layout.html' %}

{% block title %}Flight Confirmation{% endblock %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('promo.promos')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('promo.promos')}}">Packages
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.flights')}}">Flights Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.bookings')}}">Hotel Bookings</a>
            </li>
        </ul>
        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a href="" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Login</a>
            </li>
        </ul> -->
    </div>
</nav>
{% endblock %}

<!-- Jumbotron Block -->
{% block jumbtron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        <h1 class="display-4">Thank you for doing business with us<h1>
        <p><a href="{{url_for('promo.promos')}}" class="btn btn-primary">Return to Packages</a></p>  
    </div>
</div>
{% endblock %}

{% block footer %}
<div class="container-fluid bg-light mt-3 py-3">
    <span class="text-muted">This is created for ISPROJ2</span>
</div>
{% endblock %}

app/promo/templates/flightbooking.html
{% extends 'layout.html' %}

<!-- Title -->
{% block title %} Flight Booking {% endblock %}

<!-- Navbar Block -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('promo.promos')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('promo.promos')}}">Packages
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.flights')}}">Flights Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.bookings')}}">Hotel Bookings</a>
            </li>
        </ul>
        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a href="" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Login</a>
            </li>
        </ul> -->
    </div>
</nav>
{% endblock %}

<!-- Jumbotron Block -->
{% block jumbtron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Flight Booking Request</h1>
        <p class="lead">Please enter the require fields for your Flight Booking Request</p>
        <p class="lead">An email will be replied to you within 1 working day</p>
    </div>
</div>
{% endblock %}
<!-- Content -->
{% block content %}
<div class="container">
    {% from "_formhelper.html" import render_field %}
    <form action="{{ url_for('promo.flights') }}" method="post">
        {{form.csrf_token}}
        <div class="row">
            <div class="col">
                <!-- email -->
                {{ render_field(form.email, class="form-control", placeholder="ex. email@address.com") }}
                <!-- place_to -->
                {{ render_field(form.place_from, class="form-control", placeholder="ex. Manila") }}
                <!-- place_from -->
                {{ render_field(form.place_to, class="form-control", placeholder="ex. Palawan") }}
                <!-- departure_date -->
                {{ render_field(form.departure_date, class="form-control", placeholder="ex.mm-dd-yyyy") }}
            </div>
            <div class="col">
                <!-- arrival_date -->
                {{ render_field(form.arrival_date, class="form-control", placeholder="ex. mm-dd-yyyy") }}
                <!-- budget_range -->
                {{ render_field(form.budget_range, class="form-control", placeholder="ex. 500.00") }}
                <!-- head_count -->
                {{ render_field(form.head_count, class="form-control", placeholder="ex. 5") }}
            </div>
        </div>
        {{ form.recaptcha() }}
        {{ form.submit(class_='btn btn-block btn-primary')}}
    </form>
</div>
{% endblock %}

<!-- Footer -->
{% block footer %}
<div class="container-fluid bg-light mt-3 py-3">
    <span class="text-muted">This is created for ISPROJ2</span>
</div>
{% endblock %}

app/promo/templates/flightconfirmation.html
{% extends 'layout.html' %}

{% block title %}Flight Confirmation{% endblock %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('promo.promos')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('promo.promos')}}">Packages
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.flights')}}">Flights Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.bookings')}}">Hotel Bookings</a>
            </li>
        </ul>
        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a href="" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Login</a>
            </li>
        </ul> -->
    </div>
</nav>
{% endblock %}

<!-- Jumbotron Block -->
{% block jumbtron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        <h1 class="display-4">Thank you for your reservation!</h1>
        <p class="lead">An email will be replied to you within 1 working day for confirmation of your request</p>
        <p><a href="{{url_for('promo.promos')}}" class="btn btn-primary">Return to Packages</a></p> 
        <p><a href="{{url_for('promo.bookings')}}" class="btn btn-primary">Request Hotel Booking</a></p> 
    </div>
</div>
{% endblock %}

{% block footer %}
<div class="container-fluid bg-light mt-3 py-3">
    <span class="text-muted">This is created for ISPROJ2</span>
</div>
{% endblock %}

app/promo/templates/getpackage.html
<!-- {% for package in packages %}
<h1>This is for promo: {{ package.package_id }}</h1>
<h2>{{ package.package_description }}</h2>
{% endfor %} -->
{% extends 'layout.html' %}

{% block title %} Package {% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('promo.promos')}}">Packages
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.flights')}}">Flights Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.bookings')}}">Hotel Bookings</a>
            </li>
        </ul>
        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a href="" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Login</a>
            </li>
        </ul> -->
    </div>
</nav>
{% endblock %}

{% block jumbtron %}
    <div class="jumbotron jumbotron-fluid">
        {% for package in packages %}
        <div class="text-center">
            <h1 class="display-3">{{ package.package_name }}</h1>
            <p class="lead">{{ package.package_description }}</p>
            <p class="lead">PHP {{ package.package_price }}</p>
            <form action="{{ url_for('promo.pay', package_id=package.package_id) }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="{{ pubkey }}"
                
                data-name="{{ package.package_name }}"
                data-description="PHP {{ package.package_price }}"
                data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                data-locale="auto">
            </script>
            </form>
        </div>
        {% endfor %}
    </div>  
{% endblock %}

app/promo/templates/hotelbooking.html
{% extends "layout.html" %}

<!-- Title -->
{% block title %} Hotel Booking {% endblock %}

<!-- Navbar -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('promo.promos')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('promo.promos')}}">Packages
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.flights')}}">Flights Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.bookings')}}">Hotel Bookings</a>
            </li>
        </ul>
        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a href="" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Login</a>
            </li>
        </ul> -->
    </div>
</nav>
{% endblock%}

<!-- Jumbotron Block -->
{% block jumbtron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Hotel Booking Request</h1>
        <p class="lead">Please enter the require fields for your Hotel Booking Request</p>
        <p class="lead">An email will be replied to you within 1 working day</p>
    </div>
</div>
{% endblock %}

<!-- Content -->
{% block content %}
<div class="container">
    {% from "_formhelper.html" import render_field %}
    <form action="{{url_for('promo.bookings')}}" method="post">
        {{form.csrf_token}}
        <div class="row">
            <div class="col">
                <!-- email -->
                {{ render_field(form.email, class="form-control", placeholder="email@example.com") }}
                <!-- place_to -->
                {{ render_field(form.hotel_location, class="form-control", placeholder="ex. Manila") }}
                <!-- place_from -->
                {{ render_field(form.check_in_date, class="form-control", placeholder="") }}
            </div>
            <div class="col">
                <!-- departure_date -->
                {{ render_field(form.check_out_date, class="form-control", placeholder="") }}
                <!-- arrival_date -->
                {{ render_field(form.number_of_rooms, class="form-control", placeholder="ex. 2") }}
                <!-- budget_range -->
                {{ render_field(form.budget_range, class="form-control", placeholder="ex. 500.00") }}
            </div>
        </div>
        {{ form.recaptcha() }}
        {{ form.submit(class_='btn btn-block btn-primary')}}
    </form>
</div>
{% endblock %}

<!-- Footer -->
{% block footer %}
<div class="container-fluid bg-light mt-3 py-3">
    <span class="text-muted">This is created for ISPROJ2</span>
</div>
{% endblock %}

app/promo/templates/hotelconfirmation.html
{% extends 'layout.html' %} 

{% block title %}Flight Confirmation{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('promo.promos')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('promo.promos')}}">Packages
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.flights')}}">Flights Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.bookings')}}">Hotel Bookings</a>
            </li>
        </ul>
        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a href="" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Login</a>
            </li>
        </ul> -->
    </div>
</nav>
{% endblock %}

<!-- Jumbotron Block -->
{% block jumbtron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        <h1 class="display-4">Thank you for your reservation!</h1>
        <p class="lead">An email will be replied to you within 1 working day for confirmation of your request</p>
        <p>
            <a href="{{url_for('promo.promos')}}" class="btn btn-primary">Return to Packages</a>
        </p>
        <p>
            <a href="{{url_for('promo.flights')}}" class="btn btn-primary">Request Flight Reservation</a>
        </p>
    </div>
</div>
{% endblock %} 
{% block footer %}
<div class="container-fluid bg-light mt-3 py-3">
    <span class="text-muted">This is created for ISPROJ2</span>
</div>
{% endblock %}

app/promo/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block navbar %} {% endblock %} 
    {% block jumbtron %} {% endblock %} 
    {% block content %} {% endblock %}
    
    <div class="footer">
        {% block footer %} {% endblock %}
    </div>
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>

</html>

app/promo/templates/packages.html
{% extends 'layout.html' %}

<!-- Title -->
{% block title %} Packages {% endblock %}

<!-- Navbar Block -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('promo.promos')}}">Packages
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.flights')}}">Flights Bookings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('promo.bookings')}}">Hotel Bookings</a>
            </li>
        </ul>
        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a href="" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Login</a>
            </li>
        </ul> -->
    </div>
</nav>

{% endblock %}

<!-- Jumbotron Block -->
{% block jumbtron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Packages</h1>
        <p class="lead">Choose your packages</p>
    </div>
</div>
{% endblock %}

<!-- Content Block -->
{% block content %}
<div class="container">
    {% for item in packages|batch(3) %}
    <div class="card-deck">
        {% for package in item %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title" href="">{{ package.package_name }}</h4>
                <p class="card-text">{{ package.package_description }}</p>
                <p class="card-text">{{ package.package_price }}</p>
                <a href="{{ url_for('promo.package', package_id=package.package_id)}}" class="btn btn-primary">Click here to view</a>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last Updated at {{ package.package_updated.strftime('%B %d, %Y') }}</small>
            </div>
        </div>
        {% endfor %}
    </div>
    <br> {% endfor %}
</div>
{% endblock %}