app/users/routes.py
"""
This is the User Routes
"""
from flask import Blueprint, render_template, redirect, url_for
from app.models import Packages, HotelBookings, FlightBooking, DB
from flask_user import login_required
from datetime import datetime
from app.users import forms
from app.models import Packages

MOD_USER = Blueprint('main', __name__, template_folder='templates',
                     static_folder='static', static_url_path='/%s' % __name__)


@MOD_USER.route('/user')
@login_required
def homepage():
    """ User Homepage """
    flights = FlightBooking.query.order_by(
        FlightBooking.fbooking_id.desc()).all()
    hotels = HotelBookings.query.order_by(
        HotelBookings.hbooking_id.desc()).all()
    packages = Packages.query.order_by(Packages.package_id.desc()).all()
    return render_template("homepage.html", flights=flights, hotels=hotels, packages=packages)


@MOD_USER.route('/user/createpromo', methods=['POST', 'GET'])
@login_required
def promo():
    """ Promo Creation page """
    form = forms.PackagesForm()
    if form.validate_on_submit():
        package = Packages(package_name=form.package_name.data, package_description=form.description.data,
                           package_price=form.package_price.data, package_createtime=datetime.today(), package_updated=datetime.today())
        DB.session.add(package)
        DB.session.commit()
        return redirect( url_for("main.homepage", code=307))
    print(form.errors)
    return render_template('createpackage.html', form=form)


@MOD_USER.route('/user/flightdelete/confirm/<int:fbooking_id>')
@login_required
def fdelete(fbooking_id):
    """ Flight Deletion """
    flights = FlightBooking.query.get_or_404(fbooking_id)
    DB.session.delete(flights)
    DB.session.commit()
    return redirect(url_for('main.homepage')) 


@MOD_USER.route('/user/hoteldelete/confirm/<int:hbooking_id>')
@login_required
def hdelete(hbooking_id):
    """ Flight Deletion """
    hotel = HotelBookings.query.get_or_404(hbooking_id)
    DB.session.delete(hotel)
    DB.session.commit()
    return redirect(url_for('main.homepage'))


@MOD_USER.route('/user/packagedelete/confirm/<int:package_id>')
@login_required
def pdelete(package_id):
    """ Flight Deletion """
    packages = Packages.query.get_or_404(package_id)
    DB.session.delete(packages)
    DB.session.commit()
    return redirect(url_for('main.homepage')) 

@MOD_USER.route('user/check')
@login_required
def check():
    """ Email Search """
    flights = FlightBooking.query.filter(FlightBooking.fbooking_email.endswitch('@gmail.com')).all();
    hotels = HotelBookings.query.filter(HotelBooking.hbooking_email.endswitch('@gmail.com')).all();
    return render_template("availed.html", flights=flights, hotels=hotels)

app/users/templates/availed.html
{% extends 'layout.html' %}

<!-- Title -->
{% block title %} Homepage {% endblock %}

<!-- Navbar -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('main.homepage')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.homepage')}}">
                    <span class="sr-only">(current)</span>
                </a>
            </li>
           <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.promo')}}">Promo Create</a>
            </li>

        </ul>
        <ul class="navbar-nav">
            {% if call_or_get(current_user.is_authenticated) %}
            <li class="nav-item">
                <a href="{{ url_for('promo.promos') }}" class="nav-link">Promo Pages</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('user.profile') }}" class="nav-link">{{ current_user.username }}</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('user.logout') }}" class="nav-link">Sign out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{{ url_for('user.login') }}" class="nav-link">Sign in</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}

<!-- Content -->
{% block content %}
<div class="container">

<a href="{{ url_for('main.check') }}">Check Availed</a>

    <h1>Flights</h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Email</th>
                <th>Departure Location</th>
                <th>Arrival Location</th>
                <th>Departure Date</th>
                <th>Arrival Date</th>
                <th>Budget Range</th>
                <th>Head Count</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in flights %}
            <tr>
                <td>{{ item.fbooking_email }}</td>
                <td>{{item.fbooking_departure}}</td>
                <td>{{item.fbooking_arrival}}</td>
                <td>{{item.fbooking_departure_date.strftime('%b %d, %Y')}}</td>
                <td>{{item.fbooking_arrival_date.strftime('%b %d, %Y')}}</td>
                <td>{{item.fbooking_budget_range}}</td>
                <td>{{item.fbooking_head_count}}</td>
                <td><a href="{{url_for('main.fdelete', fbooking_id=item.fbooking_id)}}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h1>Hotels</h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Email</th>
                <th>Booking Location</th>
                <th>Check In Date</th>
                <th>Check Out Date</th>
                <th>Number of Rooms</th>
                <th>Budget Range</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in hotels %}
            <tr>
                <td>{{ item.hbooking_email }}</td>
                <td>{{item.hbooking_location}}</td>
                <td>{{item.hbooking_check_in.strftime('%b %d, %Y')}}</td>
                <td>{{item.hbooking_check_out.strftime('%b %d, %Y')}}</td>
                <td>{{item.hbooking_number_of_rooms}}</td>
                <td>{{item.hbooking_budget_range}}</td>
                <td>
                    <a href="{{url_for('main.hdelete', hbooking_id=item.hbooking_id)}}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/users/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM-FCTH - ADMIN</title>

    <!-- Bootstrap -->
    <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
        crossorigin="anonymous">

    <!-- In-lining styles to avoid needing a separate .css file -->
    <style>
        hr {
            border-color: #cccccc;
            margin: 0;
        }

        .no-margins {
            margin: 0px;
        }

        .with-margins {
            margin: 10px;
        }

        .col-centered {
            float: none;
            margin: 0 auto;
        }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
    <![endif]-->
</head>


<body>
    {% block body %}
    <div id="header-div" class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="{{ url_for('main.homepage') }}" class="navbar-brand">CRM-FCTH</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-nav mr-auto">
            <a href="{{ url_for('main.homepage') }}" class="nav-link">Overviews</a>
        </div> 
        <div class="navbar-nav ml-auto">
            <a href="{{ url_for('promo.promos') }}" class="nav-link">Promo Pages</a>
            {% if call_or_get(current_user.is_authenticated) %}
            <a href="{{ url_for('user.profile') }}" class="nav-link">{{ current_user.username }}</a>
            <a href="{{ url_for('user.logout') }}" class="nav-link">Sign out</a>
            {% else %}
            <a href="{{ url_for('user.login') }}" class="nav-link">Sign in</a>
            {% endif %}
        </div>
    </div>
    {% block menu %}
<!--     <div id="menu-div" class="with-margins">
        <a href="{{ url_for('main.homepage') }}">Home</a>
        {% if call_or_get(current_user.is_authenticated) %} &nbsp; | &nbsp;
        <a href="{{ url_for('user.profile') }}">User profile</a>
        {% endif %}
    </div> -->
    {% endblock %}
    <hr class="no-margins" />

    <div id="main-div" class="with-margins">
        {# One-time system messages called Flash messages #} {% block flash_messages %} {%- with messages = get_flashed_messages(with_categories=true)
        -%} {% if messages %} {% for category, message in messages %} {% if category=='error' %} {% set category='danger'
        %} {% endif %}
        <div class="alert alert-{{category}}">{{ message|safe }}</div>
        {% endfor %} {% endif %} {%- endwith %} {% endblock %} {% block main %}{% block content %}{% endblock %}{% endblock %}
    </div>

    <br/>
    <hr class="no-margins" />
    <div id="footer-div" class="">
        <div class="float-left">CRM-FCTH v1.0</div>
        <div class="float-right">&copy; 2017 ISPROJ2</div>
    </div>
    {% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- <script src="//code.jquery.com/jquery-1.11.0.min.js"></script> -->
    <!-- Bootstrap -->
    <!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

app/users/templates/createpackage.html
{% extends "layout.html" %}

<!-- Title -->
{% block title %} Hotel Booking {% endblock %}

<!-- Navbar -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('main.homepage')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.homepage')}}">
                    <span class="sr-only">(current)</span>
                </a>
            </li>
           <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.promo')}}">Promo Create</a>
            </li>

        </ul>
        <ul class="navbar-nav">
            {% if call_or_get(current_user.is_authenticated) %}
            <li class="nav-item">
                <a href="{{ url_for('promo.promos') }}" class="nav-link">Promo Pages</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('user.profile') }}" class="nav-link">{{ current_user.username }}</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('user.logout') }}" class="nav-link">Sign out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{{ url_for('user.login') }}" class="nav-link">Sign in</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock%}

<!-- Jumbotron Block -->
{% block jumbtron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Create Package</h1>
        <p class="lead">Please enter the require fields for your Hotel Booking Request</p>
        <p class="lead">An email will be replied to you within 1 working day</p>
    </div>
</div>
{% endblock %}

<!-- Content -->
{% block content %}
<div class="container">
    {% from "_formhelper.html" import render_field %}
    <form action="{{ url_for('main.promo')}}" method="post">
        {{form.csrf_token}}
        <div class="row">
            <div class="col">
                <!-- name -->
                {{ render_field(form.package_name, class="form-control", placeholder="ex. Trip to Cebu") }}
                <!-- description -->
                {{ render_field(form.description, class="form-control", placeholder="Package Description") }}
                <!-- price -->
                {{ render_field(form.package_price, class="form-control", placeholder="10000") }}
            </div>
        </div>
        {{ form.recaptcha() }} 
        {{ form.submit(class_='btn btn-block btn-primary')}}
    </form>
</div>
{% endblock %}

<!-- Footer -->
{% block footer %}
<div class="container-fluid bg-light mt-3 py-3">
    <span class="text-muted">This is created for ISPROJ2</span>
</div>
{% endblock %}

app/users/templates/flask_user/login.html
{% extends 'flask_user/public_base.html' %} 

{% block content %} 
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<h1>{%trans%}Sign in{%endtrans%}</h1>

<form action="" method="POST" class="form" role="form">
    {{ form.hidden_tag() }} 
    {# Username or Email field #} 
    {% set field = form.username if user_manager.enable_username else form.email %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        {# Label on left, "New here? Register." on right #}
        <div class="d-flex">
            <div class="col-xs-6">
                <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
            </div>
            <div class="col-xs-6 ml_auto">
                {% if user_manager.enable_register and not user_manager.require_invitation %}
                <a href="{{ url_for('user.register') }}" tabindex='190'>
                    {%trans%}New here? Register.{%endtrans%}
                </a>
                {% endif %}
            </div>
        </div>
        {{ field(class_='form-control', tabindex=110) }} {% if field.errors %} {% for e in field.errors %}
        <p class="help-block" class="text-danger">{{ e }}</p>
        {% endfor %} {% endif %}
    </div>

    {# Password field #} {% set field = form.password %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        {# Label on left, "Forgot your Password?" on right #}
        <div class="d-flex">
            <div class="col-xs-6">
                <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
            </div>
            <br>
            <div class="col-xs-6 ml-auto">
                {% if user_manager.enable_forgot_password %}
                <a href="{{ url_for('user.forgot_password') }}" tabindex='195'>
                    {%trans%}Forgot your Password?{%endtrans%}</a>
                {% endif %}
            </div>
        </div>
        {{ field(class_='form-control', tabindex=120) }} {% if field.errors %} {% for e in field.errors %}
        <p class="help-block" class="text-danger">{{ e }}</p>
        {% endfor %} {% endif %}
    </div>

    {# Remember me #} 
    {% if user_manager.enable_remember_me %} 
        {{ render_checkbox_field(login_form.remember_me, tabindex=130)}}
    {% endif %} {# Submit button #} 
    {{ render_submit_field(form.submit, tabindex=180) }}
</form>

{% endblock %}

app/users/templates/homepage.html
{% extends 'layout.html' %}

<!-- Title -->
{% block title %} Homepage {% endblock %}

<!-- Navbar -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('main.homepage')}}">CRM-FCTH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.homepage')}}">
                    <span class="sr-only">(current)</span>
                </a>
            </li>
           <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.promo')}}">Promo Create</a>
            </li>

        </ul>
        <ul class="navbar-nav">
            {% if call_or_get(current_user.is_authenticated) %}
            <li class="nav-item">
                <a href="{{ url_for('promo.promos') }}" class="nav-link">Promo Pages</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('user.profile') }}" class="nav-link">{{ current_user.username }}</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('user.logout') }}" class="nav-link">Sign out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{{ url_for('user.login') }}" class="nav-link">Sign in</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}

<!-- Content -->
{% block content %}
<div class="container">

<a href="{{ url_for('main.check') }}">Check Availed</a>

    <h1>Flights</h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Email</th>
                <th>Departure Location</th>
                <th>Arrival Location</th>
                <th>Departure Date</th>
                <th>Arrival Date</th>
                <th>Budget Range</th>
                <th>Head Count</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in flights %}
            <tr>
                <td>{{ item.fbooking_email }}</td>
                <td>{{item.fbooking_departure}}</td>
                <td>{{item.fbooking_arrival}}</td>
                <td>{{item.fbooking_departure_date.strftime('%b %d, %Y')}}</td>
                <td>{{item.fbooking_arrival_date.strftime('%b %d, %Y')}}</td>
                <td>{{item.fbooking_budget_range}}</td>
                <td>{{item.fbooking_head_count}}</td>
                <td><a href="{{url_for('main.fdelete', fbooking_id=item.fbooking_id)}}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <h1>Hotels</h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Email</th>
                <th>Booking Location</th>
                <th>Check In Date</th>
                <th>Check Out Date</th>
                <th>Number of Rooms</th>
                <th>Budget Range</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in hotels %}
            <tr>
                <td>{{item.hbooking_email}}</td>
                <td>{{item.hbooking_location}}</td>
                <td>{{item.hbooking_check_in.strftime('%b %d, %Y')}}</td>
                <td>{{item.hbooking_check_out.strftime('%b %d, %Y')}}</td>
                <td>{{item.hbooking_number_of_rooms}}</td>
                <td>{{item.hbooking_budget_range}}</td>
                <td>
                    <a href="{{url_for('main.hdelete', hbooking_id=item.hbooking_id)}}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
        <h1>Packages</h1>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Package Name</th>
                    <th>Package Description</th>
                    <th>Price</th>
                    <th>Creation Date</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in packages %}
                <tr>
                    <td>{{ item.package_name }}</td>
                    <td>{{item.package_description}}</td>
                    <td>{{item.package_price}}</td>
                    <td>{{item.package_createtime.strftime('%b %d, %Y')}}</td>
                    <td>
                        <a href="{{url_for('main.pdelete', package_id=item.package_id)}}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
</div>
{% endblock %}